### ISSUE TITLE
Support non-omnibus installations

### ISSUE THREAD

**Issue by saily** [MatthiasLohr/munin-plugins-gitlab#1]
- support MySQL database connector
- support more configuration options for db-connection

**Comment by MatthiasLohr** [comment]
Hey,

thank you for your improvement idea! Does ab9bba6 solve that for you?

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
Seems to work, so i'll close this ticket.

**Comment by saily** [comment]
Hi there, thank you vey much for your quick response, unfortunately i did not have time to test, but will reopen if it did not work.

**Comment by MatthiasLohr** [comment]
Ok, thank you!

**Comment by saily** [comment]
I wrote a comment to your commit, thanks again for the quick fix, but i see no `dsn` option for python `MySQLdb` connector. It seems to be unsupported.

**Comment by saily** [comment]
maybe you can pick some ideas from here: https://github.com/saily/redmine_stats

**Comment by MatthiasLohr** [comment]
Sry for the typo, i meant "patch" of course. Now, a special kind of dsn is supported ;)

Please take a look at the README file for an example.

**Comment by MatthiasLohr** [comment]
@saily, anything new about this topic?

**Comment by saily** [comment]
Found some more issues, so i postponed this:
- Table name prefixe `gitlab.` is missing on manual install (for example there's no table `gitlab.issues`, just `issues`). 
- There's no `data-dir` on manual installations [as you hardwired it here](https://github.com/MatthiasLohr/munin-plugins-gitlab/blob/master/lib/gitlab.py#L12)

**Comment by MatthiasLohr** [comment]
@saily, for your first point, the gitlab schema, there's now a option available for setting the postgresql search path (see #4)

I'm working on the second point.

**Comment by MatthiasLohr** [comment]
@saily Do you have special whishes for "more options for db-configuration"?

**Comment by saily** [comment]
currently i'm fine with it. thanks a lot, closing this.
