### ISSUE TITLE
Support for todos monitoring

### ISSUE THREAD

**Issue by tnir** [MatthiasLohr/munin-plugins-gitlab#16]
For [ToDo](https://about.gitlab.com/2016/03/02/gitlab-todos-feature-highlight/)-driven development, GitLab admins may want to monitor the number of undone ToDos.

**Comment by MatthiasLohr** [comment]
Hey,

would you please take a look at the ```gitlab_todos_total``` plugin at the ```feature/todos``` branch? Is that what you needed?

Sorry for the delay.

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
Merged.

**Comment by tnir** [comment]
@MatthiasLohr Thanks, but I hope I will be mentioned next time.

I will try this feature soon.
