### ISSUE TITLE
Introduce versioning

### ISSUE THREAD

**Issue by tnir** [MatthiasLohr/munin-plugins-gitlab#26]
We should start with git `tag` to version this project.

**Comment by tnir** [comment]
@MatthiasLohr Why not? 1.0 or 0.1?

**Comment by MatthiasLohr** [comment]
I have no reason not to. But I can't decide which versioning scheme to use. For example, we could assign the tags in analogy to the corresponding GitLab CE versions to indicate compatibility. We could of course also introduce your own versioning on the basis of https://semver.org/ - but what is the seminatic behind that? When should we increase which part of the version number? I am open to any kind of constructive suggestions for this.

**Comment by tnir** [comment]
Semver is a good starting point for this project as well. My concern is to indicate whether this project is ready for production use and to refer any version by specifying the tag. Probably there will be no API to break backward compatibility while it has rrdtool backends.

If you think this is production-ready, tag it as 1.0.0 and then increase minor version and/or patch version. Otherwise we should use 0.x (x=10 or something for this project, I think).

**Comment by MatthiasLohr** [comment]
Neither there is a "risk" for influencing monitored systems (GitLab instances) nor there are (known) problems/bugs, so yes, i would state, it's ready for production use.

What do you think?

**Comment by tnir** [comment]
@MatthiasLohr Yes, I totally agree with you that this is already after 1.0 due to these reasons.

I think some point around Oct/Nov 2015 is corresponding to 1.0 and then later commits and/or PR follow with 1.0.1, 1.0.2, ... The latest would be 1.0.15 or around according to my glance.

**Comment by MatthiasLohr** [comment]
Let's start with 1.0.0 at the current point. For future "releases" we could do more structured development using branches (if necessary) and then using tags in a proper way.

**Comment by tnir** [comment]
@MatthiasLohr Thanks 😄
