### ISSUE TITLE
SQL syntax error in gitlab_users_active when using postgres

### ISSUE THREAD

**Issue by momu** [MatthiasLohr/munin-plugins-gitlab#32]
```
Error output from gitlab_users_active:
2018/11/15-13:00:25 [2769]      Traceback (most recent call last):
2018/11/15-13:00:25 [2769]        File "/etc/munin/plugins/gitlab_users_active", line 32, in <module>
2018/11/15-13:00:25 [2769]          (day,)
2018/11/15-13:00:25 [2769]      psycopg2.ProgrammingError: syntax error at or near "1"
2018/11/15-13:00:25 [2769]      LINE 1: ... WHERE last_sign_in_at > CURRENT_TIMESTAMP - INTERVAL 1 day 
```
Changing 
https://github.com/MatthiasLohr/munin-plugins-gitlab/blob/a96d2827b59dbd803654292566b276bb958a9d39/gitlab_users_active#L31
to
`"WHERE last_sign_in_at > CURRENT_TIMESTAMP - INTERVAL '%s day' ",`
fixes it for postgres.
Unfortunately it does not work with mysql anymore. So some condition is needed.

**Comment by MatthiasLohr** [comment]
Could you create a pull request please? Thanks!

**Comment by MatthiasLohr** [comment]
Sloved by #35.
