### ISSUE TITLE
Add tracking of uploaded artifact storage

### ISSUE THREAD

**Issue by saily** [MatthiasLohr/munin-plugins-gitlab#7]
Since `gitlab-ci-multi-runner v0.7.x` you can upload artifacts to `gitlab-workhorse` which is stored on the filesystem. Administrators may want to track usage/load of this folder to put in more storage or a different file system to handle more load. 

what do you think about adding a plugin (or an additional graph to repo-size) which tracks artifacts size as well?

**Comment by MatthiasLohr** [comment]
Hey,

sounds like a great idea! But that's the first time i heard of gitlab-workhorse and how it works with GitLab CI components... Do you have some good documentation about that? Thanks in advance!

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
This seems to be the default path for omnibus installations:
```/var/opt/gitlab/gitlab-rails/shared/artifacts```

**Comment by saily** [comment]
@MatthiasLohr i'd recommend to monitor whole `.../shared` directory since it contains `cache` of runners as well as uploaded avatars, images of issues and images in wiki pages.

**Comment by MatthiasLohr** [comment]
@saily, i merged #8, so this is solved now?

**Comment by saily** [comment]
yes

**Comment by MatthiasLohr** [comment]
Thy!
